"""initial schema

Revision ID: 538eac1013db
Revises: 
Create Date: 2026-07-17 21:19:43.397882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '538eac1013db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_email'), 'email_verification', ['email'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('jnu_verified', sa.Boolean(), nullable=False),
    sa.Column('jnu_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_privacy', sa.Boolean(), nullable=False),
    sa.Column('consent_data_share', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_token_token_hash'), 'api_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_token_user_id'), 'api_token', ['user_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('mvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('runtime_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mvp_category'), 'mvp', ['category'], unique=False)
    op.create_index(op.f('ix_mvp_owner_id'), 'mvp', ['owner_id'], unique=False)
    op.create_index(op.f('ix_mvp_status'), 'mvp', ['status'], unique=False)
    op.create_table('point_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_ledger_user_id'), 'point_ledger', ['user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_status'), 'report', ['status'], unique=False)
    op.create_table('data_export_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mvp_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('include_free_text', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mvp_id'], ['mvp.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_export_request_mvp_id'), 'data_export_request', ['mvp_id'], unique=False)
    op.create_index(op.f('ix_data_export_request_status'), 'data_export_request', ['status'], unique=False)
    op.create_table('group_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('mvp_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['mvp_id'], ['mvp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_assignment_group_id'), 'group_assignment', ['group_id'], unique=False)
    op.create_table('group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('mvp_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mvp_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('publish_status', sa.String(length=20), nullable=False),
    sa.Column('upload_channel', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mvp_id'], ['mvp.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mvp_id', 'version', name='uq_artifact_version')
    )
    op.create_index(op.f('ix_mvp_artifact_mvp_id'), 'mvp_artifact', ['mvp_id'], unique=False)
    op.create_table('mvp_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mvp_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=False),
    sa.Column('route_path', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mvp_id'], ['mvp.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mvp_id')
    )
    op.create_table('test_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mvp_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('guide_text', sa.String(length=300), nullable=False),
    sa.Column('fixed_category', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['mvp_id'], ['mvp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_step_mvp_id'), 'test_step', ['mvp_id'], unique=False)
    op.create_table('export_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('export_request_id', sa.Integer(), nullable=False),
    sa.Column('exported_by', sa.Integer(), nullable=False),
    sa.Column('data_scope', sa.String(length=100), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['export_request_id'], ['data_export_request.id'], ),
    sa.ForeignKeyConstraint(['exported_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_audit_log_export_request_id'), 'export_audit_log', ['export_request_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mvp_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('first_impression', sa.Integer(), nullable=False),
    sa.Column('onboarding_ok', sa.Boolean(), nullable=False),
    sa.Column('onboarding_note', sa.Text(), nullable=False),
    sa.Column('reached_core', sa.Boolean(), nullable=False),
    sa.Column('stuck_step_id', sa.Integer(), nullable=True),
    sa.Column('stuck_note', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('improvement_note', sa.Text(), nullable=False),
    sa.Column('nps', sa.Integer(), nullable=False),
    sa.Column('penalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mvp_id'], ['mvp.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['stuck_step_id'], ['test_step.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mvp_id', 'reviewer_id', name='uq_review_once')
    )
    op.create_index(op.f('ix_review_mvp_id'), 'review', ['mvp_id'], unique=False)
    op.create_index(op.f('ix_review_reviewer_id'), 'review', ['reviewer_id'], unique=False)
    op.create_table('review_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('is_useful', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'voter_id', name='uq_vote_once')
    )
    op.create_index(op.f('ix_review_vote_review_id'), 'review_vote', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_vote_voter_id'), 'review_vote', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_vote_voter_id'), table_name='review_vote')
    op.drop_index(op.f('ix_review_vote_review_id'), table_name='review_vote')
    op.drop_table('review_vote')
    op.drop_index(op.f('ix_review_reviewer_id'), table_name='review')
    op.drop_index(op.f('ix_review_mvp_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_export_audit_log_export_request_id'), table_name='export_audit_log')
    op.drop_table('export_audit_log')
    op.drop_index(op.f('ix_test_step_mvp_id'), table_name='test_step')
    op.drop_table('test_step')
    op.drop_table('mvp_instance')
    op.drop_index(op.f('ix_mvp_artifact_mvp_id'), table_name='mvp_artifact')
    op.drop_table('mvp_artifact')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_group_assignment_group_id'), table_name='group_assignment')
    op.drop_table('group_assignment')
    op.drop_index(op.f('ix_data_export_request_status'), table_name='data_export_request')
    op.drop_index(op.f('ix_data_export_request_mvp_id'), table_name='data_export_request')
    op.drop_table('data_export_request')
    op.drop_index(op.f('ix_report_status'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_point_ledger_user_id'), table_name='point_ledger')
    op.drop_table('point_ledger')
    op.drop_index(op.f('ix_mvp_status'), table_name='mvp')
    op.drop_index(op.f('ix_mvp_owner_id'), table_name='mvp')
    op.drop_index(op.f('ix_mvp_category'), table_name='mvp')
    op.drop_table('mvp')
    op.drop_table('group')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_api_token_user_id'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_token_hash'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_email_verification_email'), table_name='email_verification')
    op.drop_table('email_verification')
    # ### end Alembic commands ###
